### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by magnett** [versluis/KVO-Demo#1]
It crashes as soon as you press done. It throws the exception below:

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<SecondViewController: 0x7fdbc2570330>: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.

By commenting out the call below, it works:
[super observeValueForKeyPath:keyPath ofObject:object change:change context:context];

**Comment by versluis** [comment]
Thanks for letting me know! This was because of the super call. Turns out that if that method is not implemented in the parent class, the app crashes. UIViewController does not implement it.

Fixed with the latest commit ;-)
